# Generated by Django 6.0.7 on 2026-09-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_orderreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(default='G‘oyangizni muhokama qilamiz.', max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default='G‘oyangizni foydalanuvchilar sevib ishlatadigan, natija beradigan raqamli mahsulotga aylantiramiz.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Zamonaviy va tezkor saytlar yaratamiz', max_length=180),
        ),
    ]
